### ISSUE TITLE
Make IntegralConstant::times an algorithms

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#100]
I like a lot the literal constants. 
I like less the provided times() extension as IMO it is not needed.
I would prefer to see these extensions as algorithms.

**Comment by ldionne** [comment]
From my experience, the `.times` extension is terribly useful. See for example [this](https://github.com/ldionne/Units-BLAS/commit/7b1f5362a856bef8222dd5e326b98f4f3c1bffe9#diff-8534909c15d1ed46f175067adfa88351R44) commit, which uses it a lot.

Also, like I said in #65, I don't think the complexity of adding a new algorithm is worth it:
What kind of structure do you need in order to implement `times`? At a glance, you would need something like an `Enumerable` with a lower bound, so that you can `pred(n)` until `n == lowerbound`. We have `Enumerable`, but there's no lower bound. Hence, we would need to introduce a new concept for that, and I think the added complexity is not worth it.

**Comment by ldionne** [comment]
If you have a way of implementing the algorithm without introducing a new concept, I'm willing to reopen and reconsider this, by the way.

**Comment by viboes** [comment]
I was thinking in applying it to `std::integral_constant`. Wouldn't this be possible?

**Comment by ldionne** [comment]
Currently, no. But why not use Hana's `integral_constant` then?

**Comment by pfultz2** [comment]
Ideally, it should apply to any IntegralConstant.

**Comment by ldionne** [comment]
It does. `IntegralConstant` is _not_ a concept; it only denotes Hana's integral constants. The concept is `Constant`, and it is more general than `IntegralConstant`; see [here](http://ldionne.com/hana/structboost_1_1hana_1_1Constant.html).

**Comment by ldionne** [comment]
What function name would you want if it were to be a free function? I think this looks a bit clunky:

```c++
times(int_<10>, []{ std::cout << "foo" << std::endl; });
```

**Comment by pfultz2** [comment]
> It does. IntegralConstant is not a concept; it only denotes Hana's integral constants. 

This is very confusing, because it has always been a concept. 

> The concept is Constant, and it is more general than IntegralConstant;

Yes, but why not have `IntegralConstant` be a refinement of `Constant` when the `value_type` is an integral(ie `std::is_integral` is true).

> What function name would you want if it were to be a free function?

Why wouldn't it be the same?

> I think this looks a bit clunky:

How so?

**Comment by ldionne** [comment]
> > It does. IntegralConstant is not a concept; it only denotes Hana's integral constants.

> This is very confusing, because it has always been a concept.

You're right, I did not realize that.


> > The concept is Constant, and it is more general than IntegralConstant;

> Yes, but why not have IntegralConstant be a refinement of Constant when the value_type is an integral(ie std::is_integral is true).

That makes sense. I'd need a name for Hana's IntegralConstants, though.


> > What function name would you want if it were to be a free function?

> Why wouldn't it be the same?
>
> > I think this looks a bit clunky:

> How so?

Well, I just think `times(int_<10>, f)` looks a bit ugly. It could be mistaken for multiplication, too. Something like `unroll(int_<10>, f)` might be better suited?

**Comment by pfultz2** [comment]
> Well, I just think times(int_<10>, f) looks a bit ugly. It could be mistaken for multiplication, too. Something like unroll(int_<10>, f) might be better suited?

Or perhaps `repeat`? Or is that already being used?

**Comment by pfultz2** [comment]
> That makes sense. I'd need a name for Hana's IntegralConstants, though.

Why not `integral_constant`?

**Comment by ldionne** [comment]
> Or perhaps repeat? Or is that already being used?

`repeat` is already being used, but that does not mean I can't bump it to something else. `repeat` is an obviously good candidate for a free version of `.times`, but we'd have to find something else for the current `repeat`, which is used to create a sequence containing `n` copies of some value.

> Why not integral_constant?

Well first, that would clash with the other names used for tags, which are capitalized (I'm still writing the reply to your message [here](http://article.gmane.org/gmane.comp.lib.boost.devel/261160)). But most importantly, `integral_constant` is [this](http://ldionne.com/hana/structboost_1_1hana_1_1IntegralConstant.html#a3548ddeed18cbfe945b7de9cb65f873b). Though I could also use `integral_c`, I guess.
