### ISSUE TITLE
[Documentation] Why it is more important to document the concrete models than the subclasses of a Concept? 

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#104]
When describing a Concept you describe the Superclasses and the Concrete models of this concept. I appreciate both. We don't see the Subclasses. Why it is more important to document the concrete models than the subclasses? 

See e.g. http://ldionne.com/hana/structboost_1_1hana_1_1Applicative.html

**Comment by ldionne** [comment]
That's a good question. I guess that's just the way it has always been done in Concept-based libraries. For example, see [Fusion](http://www.boost.org/doc/libs/1_58_0/libs/fusion/doc/html/fusion/sequence/concepts/bidirectional_sequence.html); it only states what concept a concept is a "refinement of", but not the reverse relation. I'd say knowing the subclasses is slightly less useful than knowing the superclasses, but I'm not feeling strongly against or for this. I'll ask the question on the mailing list, just to see what people think of it.

**Comment by ldionne** [comment]
Asked the question on the Boost.Devel mailing list, [here](http://thread.gmane.org/gmane.comp.lib.boost.devel/261165).

**Comment by viboes** [comment]
I'm saying this because Haskell doesn't make any differences between instances and super classes. 

```
Functor F => Applicative F
```

As the relationships between the type classes that some types must satisfy, I find the new superclass term confusing and not scalable. E.g. how would you express these relationships

```
Monoid a => Monoid (Maybe a)
(Monoid a, Monoid b) => Monoid (a, b)
Monoid a => Monoid (Dual a)
```

**Comment by ldionne** [comment]
I agree with you about superclasses being the wrong term, as was fixed by #102. If we're not using the term "superclass" anymore (and we're not anymore on develop), do you see a reason of keeping this one open? I could add the "subclasses" in a _see also_ section of type classes, as proposed [here](http://article.gmane.org/gmane.comp.lib.boost.devel/261171). Would that be satisfying?

**Comment by viboes** [comment]
Louis, be free to close any issue I've created. My intention is just to show you that there is some alternatives. Up to you to make the choice.

**Comment by ldionne** [comment]
I understand. My goal is not to close as many issues as possible, but rather to find an appropriate resolution for each of them. I'll let this sleep for a while and see what else may come up on the mailing list, and then I'll see what I do.

**Comment by ldionne** [comment]
Closing this in favour of #129.
