### ISSUE TITLE
[Foldable] Foldable unpack versus fold_transform

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#107]
Hana uses transform instead of map. I don't find intuitive at all the name `unpack`. What about `fold_transform`?

**Comment by pfultz2** [comment]
I find the name `unpack` very intuitive, and `fold_transform` makes no sense, since its doing neither a transform nor a fold. Also this is one of the areas where Hana might inherit from Fit. Fit has `unpack` as well.

**Comment by ldionne** [comment]
> Hana uses transform instead of map.

Yes, for 1. the resemblance with `std::transform` and 2. the name conflict with Hana's `Map` data structure.

> I don't find intuitive at all the name unpack. What about fold_transform?

I agree with @pfultz2 here. `unpack` is specified as follows:

```c++
unpack([x1, ..., xn], f) == f(x1, ..., xn)
```

This bears little to no resemblance to a fold or a transform, and I think it is very intuitive to think of it as `unpack`ing a sequence into a function.

**Comment by viboes** [comment]
Sorry, I misunderstood it. The standard uses `std::apply`for this function when `[]` is a `std::tuple`.

**Comment by ldionne** [comment]
Yes, this is `std::apply` with the arguments reversed. The rationale for the order of arguments and the name is available [here](http://ldionne.com/hana/structboost_1_1hana_1_1Foldable.html#a0e3e724580e826eaa39a934eefa2b328).
