### ISSUE TITLE
Confussion between the concrete type and the type constructor

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#110]
Sometimes we consider the data type Tag as been the model of the Concept: e. g. `Tuple` is declared as a concrete type of a `Functor`  and as a concrete type of a `Foldable`. 

However `Functor` has instances `F` such that

"
Given `F` a `Functor`, the signature is `transform:F(T)×(T→U)→F(U)`
"

and `Foldable` has instances F(T) such
"
Given a Foldable xs of data type F(T), a function f:S×T→S and an initial state s of data type S, the signatures for fold.left are

fold.left:F(T)×S×(S×T→S)→S
"

How Tuple can be a model of Foldable?

**Comment by ldionne** [comment]
IIUC, you are asking why `Tuple` is both defined as a `F(T)` and a `F`, in different concepts, right? That's just an abuse of notation. A `Foldable` is a `F` too.

**Comment by ldionne** [comment]
Ok, so technically, what should be written is:

Given a tag `F` which is a `Foldable`, an object `xs` of tag `F` and a function `f` of type `S x T -> S`, the signature of `fold.left` is 

```
    fold.left : F(T) x S x (S x T -> S) -> S
```

However, I think the way it is currently written is also perfectly comprehensible.

**Comment by viboes** [comment]
I agree. A `Foldable is a type constructor, and as such must be defined. What about

Given `F` a `Foldable`, the signature of `fold.left` is 
```
    fold.left : F(T) x S x (S x T -> S) -> S
```

**Comment by ldionne** [comment]
Works for me.
