### ISSUE TITLE
[Associative] Set theoretic operations missing from the interface

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#119]
At least the following functions are missing from the interface of associative sequences:

- [x] set intersection
- [x] set union
- [x] set difference
- [x] symmetric set difference
- [x] are two sets disjoint?

**Comment by ldionne** [comment]
@rbock IIRC, you were the one to originally request these features on the Boost.Devel mailing list. Right now, I'm struggling to define what should the intersection/union/difference of two maps be. For sets, it's easy because it's just a bunch of keys. But for maps, should the values from the first map or the second map be retained in the resulting container? Should the intersection only contain key/value pairs where both the key __and__ the value are equal in both maps? If you have any opinion regarding how this should be treated, please let me know.

**Comment by rbock** [comment]
Personally, I would not offer intersection/union/difference for maps.

Maybe if the values themselves were sets. Then the values of the resulting map could be the intersection etc, but that seems like a very special case (and I have no idea if anyone would ever need something like that).

**Comment by ldionne** [comment]
> Personally, I would not offer intersection/union/difference for maps.

Makes sense as a first step.
