### ISSUE TITLE
Quickstart documentation

### ISSUE THREAD

**Issue by camio** [ldionne/hana#137]
missing '#include <string>' which is required for members of Fish, Cat, Dog, etc.

**Comment by ldionne** [comment]
Do you mean `#include <string>`? I can't say "first, let's include the library" and include `<string>` too, and it would feel like making the reader lose its time to specify "hey, don't forget to `#include <string>`".

**Comment by camio** [comment]
When I went through the example in the docs it was just a bit awkward when I was trying to reproduce the code in my own file by copy-paste. I got a compilation error and then realized I needed some more includes. I imagine most people going through the quick start in that way will run into the issue.

Also, related to this is that "using namespace boost::hana::literals" isn't in the documentation but is required for compilation of part of the examples. I ran into that as well and actually didn't figure out how to fix it until I looked into quickstart.cpp directly.

**Comment by ldionne** [comment]
Fixed. The tutorial will be updated when I push to `master`, after the review. Thanks for the report.
