### ISSUE TITLE
Add a comparaision with n4381

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#148]
n4381- Suggested Design for Customization Points [1] uses two layers and overload instead of Tags.

It will be great if we can find a comparison on the rationale. 

See #144 

[1] http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4381.html

**Comment by ldionne** [comment]
You are right that this would be the _correct_ thing to do, but it's slightly out of scope for Hana and it would be better handled by a separate paper/blog post. But I really don't have time for that.

**Comment by viboes** [comment]
No problem. It was just an idea to improve the understanding of the Hana design. You can close it.

**Comment by ldionne** [comment]
I'll close this, but please let me know if you ever write something about that (paper/blog). A comprehensive survey of the different techniques for providing customization points would be nice to have for the C++ community as a whole.

**Comment by viboes** [comment]
He, he. My intention was that you do the job ;-)

**Comment by ldionne** [comment]
lol
