### ISSUE TITLE
Provide version of BOOST_HANA_ADAPT_STRUCT not requiring member types

### ISSUE THREAD

**Issue by jbytheway** [ldionne/hana#152]
Whenever I use Fusion's ADAPT_STRUCT macro, the first thing I do is wrap it with my own version where one does not have to provide the types (since they can be fetched with decltype).  Could hana provide this version?

So, from your example:

```
BOOST_HANA_ADAPT_STRUCT(ns::Person,
    (std::string, name),
    (int, age)
);
```

would become

```
BOOST_HANA_ADAPT_STRUCT_ALT(ns::Person,
    (name),
    (age)
);
```

or even

```
BOOST_HANA_ADAPT_STRUCT_ALT(ns::Person,
    name,
    age
);
```

This also avoids any awkward problems with types having commas in their names.

Maybe even get rid of the existing one entirely?  I can't think of a use for it.

**Comment by ldionne** [comment]
> This also avoids any awkward problems with types having commas in their names.

This is handled properly by the current macros.

> Maybe even get rid of the existing one entirely? I can't think of a use for it.

I wanted the usage of `BOOST_HANA_ADAPT_STRUCT` and `BOOST_HANA_DEFINE_STRUCT` to be as close as possible.

**Comment by ldionne** [comment]
Do you think the consistency gain is worth the extra verbosity?
In that case, we could also modify `BOOST_HANA_DEFINE_STRUCT` to make it as follows:

```c++
struct Person {
    BOOST_HANA_DEFINE_STRUCT(
        (int, age),
        (std::string, name)
    );
};
```

Notice that we don't have to pass the name of the struct anymore.

**Comment by jbytheway** [comment]
I think I would strive for DRY over consistency.  So indeed, I would prefer the less verbose versions of both of these (although check what happens with empty structs if you make that change to DEFINE_STRUCT).

**Comment by ldionne** [comment]
> (although check what happens with empty structs if you make that change to DEFINE_STRUCT).

Crap; I think empty structs can't be detected if we go that way. Is there a way to support empty structs then?

**Comment by jbytheway** [comment]
You can use one of the imperfect-but-probably-good-enough emptiness-detection macros (like the (undocumented?) BOOST_PP_IS_EMPTY); I think Boost.VMD may help here.  Or use PP_SEQs rather than variadics.

Or just not support empty structs with that macro.

**Comment by ldionne** [comment]
I think I'll leave the name of the struct there, because the gain is not that big and it would make the two macros even more inconsistent. This way, we'll just have to remember that `BOOST_HANA_ADAPT_STRUCT` requires no member types.

**Comment by ldionne** [comment]
Also, I don't want to just provide a version of `BOOST_HANA_ADAPT_STRUCT` that does not require member types, because I don't want the users to have to make a choice in this case.

**Comment by daminetreg** [comment]
@jbytheway no need to wrap the we also have both possibilties in Boost.Fusion : http://www.boost.org/doc/libs/1_59_0/libs/fusion/doc/html/fusion/adapted/adapt_struct.html. Hana is becoming always nicer. :+1:
