### ISSUE TITLE
Variance of performance measurements is unclear

### ISSUE THREAD

**Issue by jbytheway** [ldionne/hana#154]
The auto-generated graphs of performance in the documentation are very nice, but it's not clear how precise the measurements are.  It would be good if you could clarify your methods here.  For example, are you taking the average of many measurements?  If so, how many?  Mean or median?

How much variation is there?  Clearest of all to indicate this would be error bars on the plots.  Probably putting error bars on all the plots would be excessive and noisy, but maybe you could do so on one or two, just to reassure your readers that there's not too much noise.

**Comment by ldionne** [comment]
The timings are quite precise, for every time I regenerate the plots they are almost the same. However, I do not take the mean of many measurements, for that would (at the minimum) double the time to run all the benchmarks, which is unacceptable.

**Comment by jbytheway** [comment]
Just saying that much in the docs would be worthwhile.

**Comment by ldionne** [comment]
Good suggestion, thanks.
