### ISSUE TITLE
Consider using xxx_tag instead of Xxx for data type names

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#157]
It was suggested a couple of times that we should use e.g. `map_tag` instead of `Map` to denote the tag of Hana maps. One argument is that capitalized names are usually reserved for concepts in C++.

**Comment by ldionne** [comment]
Note that renaming `IntegralConstant` to `integral_constant_tag` would allow us to add a concept named `IntegralConstant` representing any `Constant` satisfying `std::is_integral<C::value_type>`. That would open the door for fixing #100 and fixing #132 by providing an automatic model of `Constant` for `IntegralConstant`s.

**Comment by ahundt** [comment]
I do like when tags are named `name_tag` and that is consistent with several other boost libraries.

**Comment by ldionne** [comment]
Closed by merging #171.
