### ISSUE TITLE
clang-3.6 segfault

### ISSUE THREAD

**Issue by sunbing81** [ldionne/hana#16]
The following snippet causes clang-3.6 segfault.

```c++
#include <boost/hana.hpp>

auto make_string = [](auto key) {
	return BOOST_HANA_STRING(key);
};

int main() {
	make_string("yes");
}
```
Am I misusing anything?

**Comment by ldionne** [comment]
First of all, I apologize for the super late answer. I was on a trip and internet access was scarce. You are misusing the `BOOST_HANA_STRING` macro; you can only pass it a string literal. That being said, the segfault is a Clang bug and I would expect a compilation error related to the macro's implementation instead.
