### ISSUE TITLE
[Documentation] Improve description of operator::adl

### ISSUE THREAD

**Issue by m-j-w** [ldionne/hana#178]
Since being inherited so often, `operator::adl` deserves a bit more attention than "...enables ADL..." in the manual. Proposition to write out ADL as "... enables argument-dependent-lookup (ADL) ..." and add a reference to something like http://en.cppreference.com/w/cpp/language/adl. That would give a better hint of its purpose and significance.

**Comment by ldionne** [comment]
`operator::adl` (and in general the whole `operator` namespace is an implementation detail. Thanks for pointing the issue out, but I will instead move `operators::adl` to the `detail` namespace to make this clear.
