### ISSUE TITLE
Provide a way to extract an arbitrary subsequence of a sequence

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#37]
Given a sequence `[x1, ..., xn]`, we need a way to extract a subsequence of the elements at indices `[i1, ..., ik]`.

**Comment by lolisa** [comment]
Nice :+1:

**Comment by ldionne** [comment]
Actually, I'm thinking that this exact operation could be used as an efficient basis for many other operations like `drop`, `take` and so on. That would require the sequences to be finite and to know their length at compile-time, but this might be a reasonable assumption to make throughout the library anyway. I'll research this further when I have more time.
