### ISSUE TITLE
Considering bii code

### ISSUE THREAD

**Issue by HaMster21** [ldionne/hana#55]
Now, I know that you are working for the formal review for the boost inclusion, but in the mean time I'd like to play around with hana, and I'd like it to be easy to integrate. I don't know if you are following up on this, but there are efforts to make [bii](https://www.biicode.com) a dependency management tool for C++ project and they are heading towards [open-sourcing](https://github.com/biicode/biicode) the whole thing.

One upside would be that boost is already there and bii is pulling dependencies automagically :boat:

So what do you thing about trying to set up a block for hana there to make it easier to play around with hana?

**Comment by ldionne** [comment]
I think that's a good idea, and if biicode becomes big then it's going to be a no-brainer. I'll try to look into it, but right now I have more urgent things to do so it might have to wait for a bit. Also, if you want to try Hana right now, it should just be a matter of cloning the repository; Hana has no hard dependency on Boost, so all you need is a working C++14 compiler.

**Comment by HaMster21** [comment]
I have a toy project that is already using hana, and I was getting along. bii just brings some :lollipop: candy with it.

I'll likely have some time during the weekend, lets see if I can prepare a pull that sets you up for bii. We'll all be better off I you keep concentrating on hana itself I guess :+1:

**Comment by ldionne** [comment]
A pull request would be terrific!

**Comment by Manu343726** [comment]
Looking very briefly at the root `CMakeLists.txt` seems like most of the manual targets setup could be avoided on biicode since bii scans your sources to create library/executable/test targets. See http://docs.biicode.com/c++/building/biicode_building.html

**Comment by ldionne** [comment]
I just read [this unfortunate new](http://blog.biicode.com/biicode-just-the-company-post-mortem/) about Biicode. Even though it is just about the company, it still seems like supporting biiicode integration has less value now. Closing this.

**Comment by Manu343726** [comment]
As with Niebler on range-v3, I would liked to advise you before, but I was
not authorized to do so. Anyway,

**Comment by Manu343726** [comment]
(The

**Comment by ldionne** [comment]
Thanks @Manu343726. I'm sorry about the new.

**Comment by Manu343726** [comment]
Sorry about the boilerplate, my phone screen gone crazy. What I was trying to say...: Self hosted FindHana.cmake that downloads the library is a good replacement I think.

**Comment by ldionne** [comment]
> Sorry about the boilerplate, my phone screen gone crazy. 

No problem.

> What I was trying to say...: Self hosted FindHana.cmake that downloads the library is a good replacement I think.

I do think that it makes the library decently easy to use. Also, since it's header only, the barrier is very low.
