### ISSUE TITLE
[String] Support fancier types of strings

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#80]
Right now, only narrow `String`s are supported. It might be nice to support fancier types of strings, like wide or UTF-XX strings. If we support this, the different ways of creating `String`s should also support these fancier char types (like the `_s` udl).

I'm not sure whether this is useful, so please comment on this issue if you need this. If enough people want it, I might implement that feature.

**Comment by ldionne** [comment]
Closing this to clean up the issue list, but people may still ask for it. A link to this issue is present in the documentation for `String`.

**Comment by cbsmith** [comment]
I'll throw my hat in the ring as saying this would be a "nice to have". Not critical though.
