### ISSUE TITLE
[Functional] Extract the utilities in a separate library or use Fit?

### ISSUE THREAD

**Issue by ldionne** [ldionne/hana#86]
The observation is that Hana's Functional module is basically the [Fit][1] library by @pfultz2. It might be nice to use Fit instead of our own mini sub-library to increase code reuse. Of course, adding a dependency is really annoying, but there might be a good way to do it.

@pfultz2 What do you think? Also, do you plan on submitting Fit for Boost review?

[1]: http://github.com/pfultz2/fit

**Comment by viboes** [comment]
I believed that both Tick and Fit were already on http://www.boost.org/community/review_schedule.html.
Paul if you add them I could manage the review of one.

**Comment by pfultz2** [comment]
> What do you think?

Its very possible. I dont know how the logistics will work since your library will go to review first.

> Also, do you plan on submitting Fit for Boost review?

Yes, there is some more work I hope to finish in the next month, and then I would like to ask for an informal review first, and then move towards a scheduling a formal review.

**Comment by pfultz2** [comment]
> I believed that both Tick and Fit were already on http://www.boost.org/community/review_schedule.html.
Paul if you add them I could manage the review of one.

I am not sure how I get added to the schedule. It looks like the Fit library is reaching much closer to formal review. If you are able to be the review manager that would be great.

**Comment by ldionne** [comment]
> > What do you think?

> Its very possible. I dont know how the logistics will work since your library will go to review first.

Oh, I don't see the "Functional" utilities as really part of Hana. I mean, they are, but they are definitely not core functionality. As far as I'm concerned they could be moved to the `detail` namespace, except that I would need to modify the examples that use them. I don't see Hana's "Functional" module as any kind of threat to Fit entering Boost, if Hana is accepted.

**Comment by pfultz2** [comment]
> As far as I'm concerned they could be moved to the detail namespace, except that I would need to modify the examples that use them.

How would the examples be modified? Would they use Fit or the `detail` namespace?

I think it is good idea for us to coordinate it together, especially since there can be subtle differences(like `hana::compose` vs `fit::compose`).

**Comment by ldionne** [comment]
> How would the examples be modified? Would they use Fit or the detail namespace?

Yes, basically. Not a large modification.


> I think it is good idea for us to coordinate it together, especially since there can be subtle differences(like hana::compose vs fit::compose).

I think so too. To give us some more time, I'll  move the Functional module to the Details module of the documentation, so it is not advertised as being part of the Boost submission. What do you think?

**Comment by pfultz2** [comment]
> I think so too. To give us some more time, I'll move the Functional module to the Details module of the documentation, so it is not advertised as being part of the Boost submission. What do you think?

Sounds good. Perhaps, there should be a note in the review that you plan to use Fit for the functional utilities, so the reviewers understand the use of the `detail` namespace in the examples.

**Comment by ldionne** [comment]
> Sounds good. Perhaps, there should be a note in the review that you plan to use Fit for the functional utilities, so the reviewers understand the use of the detail namespace in the examples.

I did not move the functional utilities to the `detail::` namespace, but only to the "Details" part of the documentation, upon which people must not rely. So there's no usage of `detail::` in the few examples that use the functional utilities. However, I'll put a note in the documentation of that module that it might be replaced by Fit, which is why it's kinda hidden right now.

**Comment by viboes** [comment]
Louis, where have you added this note?

**Comment by viboes** [comment]
@pfultz2 Paul let me know when you consider your library is ready for review and why not some dates would be good for you. I will need to do a check then so that we can add it to the review schedule.
Please let follow this privately.

**Comment by ldionne** [comment]
@viboes The note is right [there](http://ldionne.com/hana/group__group-functional.html).

**Comment by ldionne** [comment]
After thinking about this for a while, I'd rather leave Hana without dependencies and control the implementation of these function objects, which are used in a couple of implementation details of Hana.
