### ISSUE TITLE
[Question] Why Hana needs to define yet another tuple type?

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#88]
Is there any restriction on the std::tuple type that prevents Hana to use it?
Could std::tuple be integrated in Hana?

I see 
```c++
Cat garfield = animals[1_c];
```

But is tis enough?

**Comment by ldionne** [comment]
It is, but it is not documented yet. Note that `std::pair`, `std::ratio`, `std::integral_constant` and `std::integer_sequence` are also adapted and can be used with Hana. However, `std::tuple` in libc++ has a couple of bugs that makes it not 100% usable with Hana, but that's not a fundamental problem.

**Comment by ldionne** [comment]
> I see
>
> ```c++
>  Cat garfield = animals[1_c];
> ```
> But is tis enough?

I don't understand your updated question.

**Comment by ldionne** [comment]
Oh; are you asking whether I think providing sugar like `animals[1_c]` is enough to mandate creating a new tuple type? The reasons for providing a new tuple type are deeper than that. I'd say the most important one is performance; `std::tuple` implementations are usually very slow at compile-time. We can also apply interesting compile-time optimizations in algorithms if we control the exact representation of the tuple. Finally, there's the sugar.

**Comment by ldionne** [comment]
But if you prefer, you can also use `std::tuple` via the provided adapter. However, beware of slow compile-times :-).

**Comment by ldionne** [comment]
I'll assume this answers your question and close this. If it doesn't please let me know.

**Comment by viboes** [comment]
Thanks Louis for the answer. I would appreciate if the rationale is explained in the documentation.
