### ISSUE TITLE
[Question] The detailled definition of insert, is not hiding a concept?

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#95]
There a re a lot of symbols at the Hana level as all the functions are on the boost::hana namespace.
In particular we have that insert works for Sequence, Map and for Set but have different signature.

IIUC the implementation needs some kind of internal implementation shared between the all the type classes and data types that implement this function is some way. 

That is not described in the documentation, and I believe that this hides a concept.

**Comment by ldionne** [comment]
> IIUC the implementation needs some kind of internal implementation shared between the all the type classes and data types that implement this function is some way.

That is correct; `Map`, `Set` and `Sequence` all share the same `insert` "facade" function object.

> That is not described in the documentation, 

Indeed, the fact that they all share the same facade function object is an implementation detail, and that should not be documented.

> and I believe that this hides a concept.

It is possible that some kind of `Insertable` concept is hiding somewhere, but it would be helpful if you could provide something more precise. For example, what should be the functions associated to this concept and what should be the laws it respects?

Also note that I plan to revisit the interface and implementation of associative sequences as part of this year's Google Summer of Code project, so I might find this `Insertable` concept through this.

**Comment by viboes** [comment]
When I see an interface I think always as how the user can extend this interface. How the user can define a new Mapped Concept that has a insert function also?

**Comment by ldionne** [comment]
Well he can do so in his own namespace, if that's what you mean. Of course, you can't highjack Hana's namespace to put your own names in it, but that's nothing new.

**Comment by ldionne** [comment]
I'm going to close this in favour of #111, which is defining a proper AssociativeSequence concept. Such a concept would most likely include the `insert` function, which seems to be the main concern here.
