### ISSUE TITLE
[Question] isn't the datatype Tag hiding a type class?

### ISSUE THREAD

**Issue by viboes** [ldionne/hana#96]
As several types can share the same data_type, as it is the case for a Map, isn't this hiding an AssociativeMap  type class?

**Comment by ldionne** [comment]
I'm not sure I understand your question, could you please be more specific? In particular, I don't understand this part:

> several types can share the same data_type, as it is the case for a Map

It is correct that several types can share the same `datatype`. For example `decltype(int_<0>)` and `decltype(int_<1>)` are different types, but they both share the `IntegralConstant<int>` tag. But I fail to see the link with `Map`.

**Comment by viboes** [comment]
E.g. `tuple<pair<x,y>>`,  `tuple<tuple<x,y>>` and `my_named_tuple<x(y)>` all of them could be seen as an AssociativeMap, as the elements can be seen as a `Product` and the type constructor can be seen as a `Sequence` . Am I missing something?

**Comment by ldionne** [comment]
`Tuple` does not enforce the uniqueness of elements, whereas `Map` does. Also, the order of elements in a `Map` is not important to determine the equality of `Map`s, whereas it makes a difference for `Tuple`. They are really just different structures designed for different use cases.

**Comment by viboes** [comment]
ok. tuple is not correct for a map, but `my_named_tuple` could be.

**Comment by ldionne** [comment]
IIUC, your comment is about the fact that we're missing an `AssociativeSequence` concept, right? If so, that's one of the goals of my GSoC to define a proper concept for associative sequences.

**Comment by viboes** [comment]
Perfect :)

**Comment by ldionne** [comment]
Superb. Closing this in favour of #111.
